version: '3'

services:
  sh-dev:
    platform: linux/x86_64
    image: ghcr.io/shumilovsergey/sh-development:latest
    ports:
      - "5004:8000"
    restart: always
    container_name: "sh-development"
    environment:
      - ALLOWED_HOSTS= localhost 127.0.0.1
    volumes:
      - .:/code
      - ./sqlite:/sqlite
      - ./api/static:/api/static