version: '3'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:8000"
    restart: always
    container_name: "sh-dev"
    environment:
      - ALLOWED_HOSTS= localhost 127.0.0.1
    volumes:
      - .:/code
      - ./sqlite:/sqlite
      - ./api/static:/api/static
